### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by StefanGerrits2** [MarjoleinAardewijn/progressive-web-apps-1920#10]
Ik zie dat je nu in elke `app.get` nog de volledige functies heb uitgeschreven, ik zou hiervan modules maken en deze exporten met `modules.export` deze kan je dan weer importeren in je app.js met `const moduleNaamHier = require('./route/to/path)'`

**Comment by MarjoleinAardewijn** [comment]
Code is nu in modules opgedeeld.
