### ISSUE TITLE
Api key and other credentials

### ISSUE THREAD

**Issue by CountNick** [MarjoleinAardewijn/progressive-web-apps-1920#12]
I noticed your API key is out on the wild web. Might be a good practise to put this in a .env variable which you add in your .gitignore:see_no_evil: In order to make use of this you will also need the [dotenv package](https://www.npmjs.com/package/dotenv)

https://github.com/MarjoleinAardewijn/progressive-web-apps-1920/blob/efe6a01dd8d29c836d3cc702ebf0d2dfd751d12d/docs/server.js#L12

**Comment by MarjoleinAardewijn** [comment]
I tried to do that and with the `port` variable it worked great, but as soon as I added the API_KEY my app crashed without giving any errors. And I couldn't find the solution for this problem.

server.js:
```
const globalConfig = require('./config');

const config = {
        port: globalConfig.port,
        apiKey: globalConfig.masterKey,
        ...
```

**Comment by MarjoleinAardewijn** [comment]
Tried to implement it again and now it works!
