### ISSUE TITLE
Readme install packages

### ISSUE THREAD

**Issue by StefanGerrits2** [MarjoleinAardewijn/progressive-web-apps-1920#8]
In je readme staat dit:

Install all the dependencies:

    npm i express --save
    npm i nodemon --save-dev
    npm i ejs --save
    npm i node-fetch --save
    npm i gulp --save-dev
    npm i gulp-concat --save-dev
    npm i gulp-clean-css --save-dev
    npm i gulp-autoprefixer --save-dev
    npm i rimraf --save-dev
    npm i chokidar-cli --save-dev

Je kan ook simpelweg neerzetten: `npm install`. Dit installeert namelijk elke package die in je package.json file staan.

**Comment by CountNick** [comment]
Ik wilde hetzelfde zeggen! Op deze onder [usage](https://github.com/MarjoleinAardewijn/progressive-web-apps-1920#usage) staat nu ergens ```npm init``` als je hier ```npm install``` van maakt worden alle dependencies automatischa geïnstalleerd!:clown_face:

**Comment by MarjoleinAardewijn** [comment]
Thanks! Ik heb het aangepast! :)
