### ISSUE TITLE
Images folder in root

### ISSUE THREAD

**Issue by StefanGerrits2** [MarjoleinAardewijn/progressive-web-apps-1920#9]
Ik zie dat je een map images in je root hebt staan, ik denk dat dit voor de readme is?

Wat ik kan aanraden is, als je je afbeeldingen upload in een issue op github, dan maakt github automatisch een linkje aan die je vervolgens in je readme kan zetten. Dit is een handige `hack` en hoef je niet je afbeeldingen up te loaden in je repo.

**Comment by MarjoleinAardewijn** [comment]
Oke thanks dat wist ik niet! Ga ik zeker proberen! Maar ik hoef de issue daarvoor niet te committen neem ik aan toch?

**Comment by StefanGerrits2** [comment]
Nee klopt, die hoef je niet te committen. Die issues gebruik je alleen om even de afbeelding te uploaden en het linkje te kopieëren. Dan kan je de issue weer cancellen of nieuwe afbeeldingen uploaden voor nieuwe linkjes.

**Comment by MarjoleinAardewijn** [comment]
Oke thanks voor de tip! Heb het net allemaal veranderd, is inderdaad erg handig!
